### ISSUE TITLE
Build failure: similar/main/automap.cpp:1633:27: error: unused variable ‘gmi’ [-Werror=unused-variable]

### ISSUE THREAD

**Issue by Kieltux** [dxx-rebirth/dxx-rebirth#531]
Hello,
I want to update the d2x-rebirth version in the openSUSE games repository: https://build.opensuse.org/package/show/games/d2x-rebirth
But the building fails for openSUSE Leap 15.1 and openSUSE Leap 15.2.

### Environment
I use the following git version: 519c14a4076bee1ad315148efe841e053a81f947
Should be the same version as on https://www.dxx-rebirth.com/download-dxx-rebirth/
commit: 519c14a , date: 2020/07/29

#### Operating System Environment
openSUSE Leap 15.1
openSUSE Leap 15.2

### Description
Building for openSUSE Leap 15.1 and 15.2 fails with following error:
```
[  252s] similar/main/automap.cpp: In function ‘void d2x::InitMarkerInput()’:
[  252s] similar/main/automap.cpp:1633:27: error: unused variable ‘gmi’ [-Werror=unused-variable]
[  252s]    auto &&[gmi, pmi, objidx] = *iter;
[  252s]                            ^
[  254s] cc1plus: some warnings being treated as errors
```

#### Regression status

Maybe this was introduced by https://github.com/dxx-rebirth/dxx-rebirth/commit/ec6a78c481933cd190f57fc69430e5474aaedeca#diff-60c49eaaa7ec0cf223448cb7d67db18d

I think (I am not a good programmer) it should be enough to fix the build problem by adding add (void) gmi;
```
diff -Nur d2x-rebirth-0.61.git.1595387478.519c14a40/similar/main/automap.cpp new/similar/main/automap.cpp
--- d2x-rebirth-0.61.git.1595387478.519c14a40/similar/main/automap.cpp	2020-07-22 05:11:18.000000000 +0200
+++ new/similar/main/automap.cpp	2020-08-05 17:54:42.634716130 +0200
@@ -1631,6 +1631,7 @@
 	for (;;)
 	{
 		auto &&[gmi, pmi, objidx] = *iter;
+		(void) gmi;
 		if (objidx == object_none)		//found free slot!
 		{
 			MarkerState.MarkerBeingDefined = pmi;
```

**Comment by vLKp** [comment]
This fails to build under gcc-7, but is silently accepted in gcc-8 and later.  I tested on a later gcc before pushing.  gcc-7 is a supported target, so this must be fixed.

You are correct that a cast to `void` would resolve this.  However, on looking at the code, I do not see any reason for `gmi` to be saved.  I think I needed it in an earlier iteration of the loop, but the code that is now used does not need the game marker range to be part of the zipped sequence, so the problem can also be resolved by removing that range.  I will do so.

**Comment by vLKp** [comment]
The above commit resolves the failure for me with gcc-7.  Please sync and retry.

**Comment by Kieltux** [comment]
Thank you.
