### ISSUE TITLE
Failed Assert when launching a new Multiplayer game

### ISSUE THREAD

**Issue by zicodxx** [dxx-rebirth/dxx-rebirth#268]
Just noticed that upon launching a new Multiplayer game, I hit the Assert:

> Assert(!(obj->mtype.phys_info.flags & PF_STICK && obj->mtype.phys_info.flags & PF_BOUNCE));	//can't be bounce and stick

in do_physics_sim().

I tried to find out where the program sets these two flags by watching a powerup (which seem to be the culprits for this trigger) via gdb.
However

> watch d2x::Objects._M_elems[7].mtype.phys_info.flags

doesn't work as gdb complains:

> There is no member named _M_elems

**Comment by vLKp** [comment]
I can reproduce this in a build with **poison=overwrite** when I bump a door to open it.  The assert then triggers for my object (`ConsoleObject`).  I saw this while a guest in an anarchy game.  The host is able to bump doors open without issue.  The flags value in my case was `65021`, indicating that the value was poisoned and never reinitialized with a real value.

**Comment by Mako88** [comment]
I attempted to bisect the error you saw @vLKp, however many recent commits (not the latest) freeze or crash when trying to host or join a multiplayer game, so the closest I could get was one of these commits:

7ccd5373628b83b07d4d7e89f93b96dce115d87d
a59de2860e5410e388ba0b3967a6138a10778a68
e231fb7d3a39366a5fb17f3283e29a70f590941b
117d2f73e088fbd7796f5753211b8c3f0d06942d

**Comment by Mako88** [comment]
Also, @zicodxx's but only happens when powerups are set to duplicate. I bisected it and c2626ea488970e38decf109685deff643f4445f5 is the first bad commit.

**Comment by vLKp** [comment]
Regarding [comment 261145078](#issuecomment-261145078):

That bisection is incorrect.  [Default poison to 'overwrite' in debug builds](/dxx-rebirth/dxx-rebirth/commit/c2626ea488970e38decf109685deff643f4445f5) does exactly what it says in the commit message.  If you do not set a value for `poison`, and you enable `debug`, then that commit will cause `poison` to default to `overwrite` instead of `none`.  This can expose bugs elsewhere, but can be a bug only if a poison write is placed somewhere that it should not be.  Please set `poison=overwrite` in your build options and try again.

Regarding [comment 261143014](#issuecomment-261143014):

Most likely, you were led to [Poison more undefined variables](/dxx-rebirth/dxx-rebirth/commit/a59de2860e5410e388ba0b3967a6138a10778a68), which, like your other bisection, is a false hit.  That commit reveals bugs elsewhere by setting undefined data to have a value likely to cause problems.  The real bug is that there is a path which uses the value without ever initializing it.  Undefined data, by definition, can have any value, so accessing it without setting a value is always a bug.  The poison just makes the undefined value more likely to provoke a visible problem.

**Comment by Mako88** [comment]
Confirmed fixed in `master`. Closing.
