### ISSUE TITLE
Compiling fails on the Raspberry Pi as of 04e3c1e9a385a5e24bdbad4fdd631f90c7bfbe5e

### ISSUE THREAD

**Issue by joolswills** [dxx-rebirth/dxx-rebirth#176]
Recently building on the Raspberry Pi broke.

compiling with `scons raspberrypi=1`

```
similar/arch/ogl/gr.cpp: In function ‘void d1x::rpi_destroy_element()’:
similar/arch/ogl/gr.cpp:164:6: error: ‘dispman_element’ was not declared in this scope
  if (dispman_element != DISPMANX_NO_HANDLE) {
      ^
similar/arch/ogl/gr.cpp: In function ‘int d1x::rpi_setup_element(int, int, Uint32, int)’:
similar/arch/ogl/gr.cpp:237:6: error: ‘dispman_display’ was not declared in this scope
  if (dispman_display == DISPMANX_NO_HANDLE) {
      ^
similar/arch/ogl/gr.cpp:245:6: error: ‘dispman_element’ was not declared in this scope
  if (dispman_element != DISPMANX_NO_HANDLE) {
      ^
similar/arch/ogl/gr.cpp:259:59: error: ‘nativewindow’ was not declared in this scope
   vc_dispmanx_element_change_attributes ( dispman_update, nativewindow.element,
                                                           ^
similar/arch/ogl/gr.cpp:268:3: error: ‘dispman_element’ was not declared in this scope
   dispman_element = vc_dispmanx_element_add ( dispman_update, dispman_display,
   ^
similar/arch/ogl/gr.cpp:268:63: error: ‘dispman_display’ was not declared in this scope
   dispman_element = vc_dispmanx_element_add ( dispman_update, dispman_display,
                                                               ^
similar/arch/ogl/gr.cpp:276:3: error: ‘nativewindow’ was not declared in this scope
   nativewindow.element = dispman_element;
   ^
similar/arch/ogl/gr.cpp:278:2: error: ‘nativewindow’ was not declared in this scope
  nativewindow.width = display_width;
  ^
distcc[14160] ERROR: compile similar/arch/ogl/gr.cpp on localhost failed
scons: *** [similar/arch/ogl/.d1x-rebirth.gr.o] Error 1
scons: building terminated because of errors.
```

bisected to 04e3c1e9a385a5e24bdbad4fdd631f90c7bfbe5e

```
04e3c1e9a385a5e24bdbad4fdd631f90c7bfbe5e is the first bad commit
commit 04e3c1e9a385a5e24bdbad4fdd631f90c7bfbe5e
Author: Kp <kp@valhallalegends.com>
Date:   Tue Jan 26 03:45:07 2016 +0000

    Move OpenGL cpp flag tracking to SConf

:100644 100644 1def1eddff23a1d8fbba0b2f0ff8827c6bb49065 0606516548c9dbf4d11949da10f4bc98dd1ad726 M	SConstruct
```

**Comment by vLKp** [comment]
Raspberry Pi code assumes, without checking, that `OGLES` will be defined.  The cited commit should not have changed that.  Please attach full `verbosebuild=1` Raspberry Pi build logs from [Pass `archive` to prepare_environment](/dxx-rebirth/dxx-rebirth/commit/1a113700847396e5670d1eff4894cef5ea8957d4) and from [Move OpenGL cpp flag tracking to SConf](/dxx-rebirth/dxx-rebirth/commit/04e3c1e9a385a5e24bdbad4fdd631f90c7bfbe5e).  As a workaround, you can try setting `opengles=1` on the SCons command line.  The Raspberry Pi is a bit odd in that setting `raspberrypi=1` automatically sets other choices.  If that mechanism failed, OpenGL ES might not be activated.

**Comment by vLKp** [comment]
After reviewing the build log of a run with OpenGL ES enabled, I see the problem.  Please update to [Use extend for OGL defines](/dxx-rebirth/dxx-rebirth/commit/fa8ceaeb5fa0db35b10ead2f0a60d30a50e10f6c) and try again.

**Comment by joolswills** [comment]
Thanks - that fixes it :) (I did generate the logs, but you were too fast with your fix :) )
