### ISSUE TITLE
fails to build on gcc 4.9.3 (eg used on Debian Jessie)

### ISSUE THREAD

**Issue by joolswills** [dxx-rebirth/dxx-rebirth#411]
You may not want to fix this as it's an old GCC, but noticed this when rebuilding binaries for RetroPie for Debian Jessie (We are dropping support for Jessie ourselves soon). Tested on gcc 4.9 on Ubuntu machine to confirm. Works fine on newer gcc. The first error is just an assert which I removed and continued building then ran into another error.

Built from 931ea05f41fef76cf7a210bd06230128b68df8e8 (git HEAD at time of writing)

System: Ubuntu 18.10 64bit with older gcc-4.9 installed. Same fail on RPI with Debian Jessie.

end of the build log for first issue:
```
CXX d1x . similar/main/wall.cpp
similar/main/wall.cpp: In member function ‘void d1x::d_level_unique_stuck_object_state::remove_stuck_object(d1x::vcobjidx_t)’:
similar/main/wall.cpp:1321:16: error: ‘is_trivially_move_assignable’ is not a member of ‘std’
  static_assert(std::is_trivially_move_assignable<stuckobj>::value, "stuckobj move may require a check to prevent self-move");
                ^
similar/main/wall.cpp:1321:58: error: expected primary-expression before ‘>’ token
  static_assert(std::is_trivially_move_assignable<stuckobj>::value, "stuckobj move may require a check to prevent self-move");
                                                          ^
similar/main/wall.cpp:1321:59: error: ‘::value’ has not been declared
  static_assert(std::is_trivially_move_assignable<stuckobj>::value, "stuckobj move may require a check to prevent self-move");
                                                           ^
scons: *** [similar/main/.d1x-rebirth.wall.o] Error 1
scons: building terminated because of errors.
Failed target count: total=1; targets with enable_build_failure_summary=1: 1
Failed node list:
	similar/main/.d1x-rebirth.wall.o
Failed command list:
 g++-4.9 -c -g -O2 -ftabstop=4 -Wall -Werror=extra -Werror=format=2 -Werror=missing-braces -Werror=missing-include-dirs -Werror=uninitialized -Werror=undef -Werror=pointer-arith -Werror=cast-qual -Werror=missing-declarations -Werror=redundant-decls -Werror=vla -pthread -funsigned-char -std=gnu++14 -Wno-missing-field-initializers -fextended-identifiers -Werror=unused -Werror=useless-cast -fvisibility=hidden -Wsuggest-attribute=noreturn -Wlogical-op -Wold-style-cast -Wno-sign-compare -DPHYSFS_DEPRECATED= -DNDEBUG -DRELEASE -D_REENTRANT -DDXX_BUILD_DESCENT_I -D__STDC_FORMAT_MACROS -Icommon/include -Icommon/main -I. -I/usr/include/libpng16 -I/usr/include/SDL -Id1x-rebirth/main "similar/main/wall.cpp" -o "similar/main/.d1x-rebirth.wall.o"
```

removed the assert then got a fail with:

```
CXX d1x . similar/main/playsave.cpp
CXX d1x . similar/main/net_udp.cpp
similar/main/net_udp.cpp: In function ‘void copy_truncate_string(const grs_font&, font_x_scaled_float, std::array<char, 25ul>&, const ntstring<25ul>&)’:
similar/main/net_udp.cpp:1052:43: error: ‘out’ is not a constant expression
  constexpr std::size_t outsize = out.size();
                                           ^
scons: *** [similar/main/.d1x-rebirth.net_udp.o] Error 1
scons: building terminated because of errors.
Failed target count: total=1; targets with enable_build_failure_summary=1: 1
Failed node list:
	similar/main/.d1x-rebirth.net_udp.o
Failed command list:
 g++-4.9 -c -g -O2 -ftabstop=4 -Wall -Werror=extra -Werror=format=2 -Werror=missing-braces -Werror=missing-include-dirs -Werror=uninitialized -Werror=undef -Werror=pointer-arith -Werror=cast-qual -Werror=missing-declarations -Werror=redundant-decls -Werror=vla -pthread -funsigned-char -std=gnu++14 -Wno-missing-field-initializers -fextended-identifiers -Werror=unused -Werror=useless-cast -fvisibility=hidden -Wsuggest-attribute=noreturn -Wlogical-op -Wold-style-cast -Wno-sign-compare -DPHYSFS_DEPRECATED= -DNDEBUG -DRELEASE -D_REENTRANT -DDXX_BUILD_DESCENT_I -D__STDC_FORMAT_MACROS -DDXX_VERSION_SEQ=0,59,100 -Icommon/include -Icommon/main -I. -I/usr/include/libpng16 -I/usr/include/SDL -Id1x-rebirth/main "similar/main/net_udp.cpp" -o "similar/main/.d1x-rebirth.net_udp.o"
```

Not got any further.

Please feel free to close if 4.9.3 should not work and gcc-5 or newer is to be a minimum - i will build from an older release for Jessie - the docs say 4.9.4 but I suspect it will fail on that too currently.

**Comment by joolswills** [comment]
(sconf.log added to end of issue)

**Comment by vLKp** [comment]
If the documentation says 4.9.x, then this ticket is valid.  It's only a question of whether to fix it by changing the documentation or changing the code.  I'll try to get 4.9.x working.

**Comment by joolswills** [comment]
Thanks for the quick fix.
